export enum CatActionTypes {
    API_GET_BY_BREED = 'API_GET_BY_BREED',
    API_GET_BREEDS = 'API_GET_BREEDS',
    INCREMENT_PAGE = 'INCREMENT_PAGE',
    STORE_SELECTED_BREED = 'STORE_SELECTED_BREED',
}
