export enum CatMutationTypes {
    SET_BREED_LIST = 'SET_BREED_LIST',
    SET_BREEDS_LIST = 'SET_BREEDS_LIST',
    SET_BREED_ID = 'SET_BREED_ID',
    SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
    SET_CAN_LOAD_MORE = 'SET_CAN_LOAD_MORE',
    SET_THROW_ERROR = 'SET_THROW_ERROR',
}
